name: flight-cost-optimizer
run-name: ${{
github.ref.startsWith('refs/heads/') ? github.ref.substring(11) : github.ref
}}
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run tests
        run: npm run test